# permissions for end users to view svngroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: svngroup-viewer-role
rules:
- apiGroups:
  - svn.k8s.oyasumi.club
  resources:
  - svngroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - svn.k8s.oyasumi.club
  resources:
  - svngroups/status
  verbs:
  - get
