# permissions for end users to edit svngroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: svngroup-editor-role
rules:
- apiGroups:
  - svn.k8s.oyasumi.club
  resources:
  - svngroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - svn.k8s.oyasumi.club
  resources:
  - svngroups/status
  verbs:
  - get
