# permissions for end users to edit svnservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: svnserver-editor-role
rules:
- apiGroups:
  - svn.k8s.oyasumi.club
  resources:
  - svnservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - svn.k8s.oyasumi.club
  resources:
  - svnservers/status
  verbs:
  - get
