# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/svn.k8s.oyasumi.club_svnservers.yaml
- bases/svn.k8s.oyasumi.club_svngroups.yaml
- bases/svn.k8s.oyasumi.club_svnrepositories.yaml
- bases/svn.k8s.oyasumi.club_svnusers.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_svnservers.yaml
#- patches/webhook_in_svngroups.yaml
#- patches/webhook_in_svnrepositories.yaml
#- patches/webhook_in_svnusers.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_svnservers.yaml
#- patches/cainjection_in_svngroups.yaml
#- patches/cainjection_in_svnrepositories.yaml
#- patches/cainjection_in_svnusers.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
