name: Build Versioned

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: v3.9.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PERSONAL_ACCESS_TOKEN }}

      - name: Declare Variables
        id: variables
        run: |
          echo "set VERSION=${GITHUB_REF#refs/tags/}"
          echo "::set-output name=VERSION::${GITHUB_REF#refs/tags/}"

      - name: Build and Push svn-operator
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/svn-operator:${{ steps.variables.outputs.VERSION }}

      - name: Build and Push svn-server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.svnserver
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/svn-server:${{ steps.variables.outputs.VERSION }}

      - name: Build Manifests
        run: |
          cd config/manager
          kustomize edit set image controller=ghcr.io/genkami/svn-operator:${{ steps.variables.outputs.VERSION }}
          cd ../default
          kustomize cfg set . svn-server-image ghcr.io/${{ github.repository_owner }}/svn-server:${{ steps.variables.outputs.VERSION }}
          cd ../..
          kustomize build config/default > artifacts/svn-operator.yaml

      - name: Upload Manifests
        uses: actions/upload-artifact@v2
        with:
          name: svn-operator.yaml
          path: |
            artifacts/svn-operator.yaml
